# Generated by Django 4.2 on 2023-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioconvert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtotext',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='speech-to-text-audio/'),
        ),
        migrations.AddField(
            model_name='speechtotext',
            name='transcript',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
